apiVersion: v2
name: my-parent-chart
description: A parent helm chart managing two subcharts
type: application
version: 4.5.8
appVersion: "4.5.15"

dependencies:
  - name: child-1
    version: 4.5.8
    repository: "file://./charts/child-1"
  - name: child-2
    version: 4.5.7
    repository: "file://./charts/child-2"
