apiVersion: v2
name: my-parent-chart
description: A parent helm chart managing two subcharts
type: application
version: 4.1.22
appVersion: "22.4.4.1.22"

dependencies:
  - name: child-1
    version: 4.1.22
    repository: "file://./charts/child-1"
  - name: child-2
    version: 4.1.22
    repository: "file://./charts/child-2"
