child-1:
  enabled: true
  ingress:
    enabled: true
  hpa:
    enabled: false 
  image:
    repository: child-1-app
    tag: "latest-9"

child-2:
  enabled: true
  ingress:
    enabled: true
  hpa:
    enabled: false
  image:
    repository: child-1-app
    tag: "latest-9"
